### ISSUE TITLE
Plugin Stopped working

### ISSUE THREAD

**Issue by catarinapereira** [ahmedmigo/Move-to-library-sketchplugin#10]
Move to library just stopped working and I'm constantly getting a message saying "Something went wrong".

**Comment by ahmedmigo** [comment]
Hello, 
yes there is some problems with the new version of sketch and I am working on the new update soon :)

**Comment by ahmedmigo** [comment]
Hello @catarinapereira,
I released a new updated.
can you update and test it and tell me ?

**Comment by stigmates** [comment]
Hi! it works agin but overides seen to be broken :-(

**Comment by ahmedmigo** [comment]
@stigmates hello, 
can you send me test case

**Comment by stigmates** [comment]
no sorry I can't because I redid my overides.
