### ISSUE TITLE
UI goes blank when clicking in window

### ISSUE THREAD

**Issue by jjmm95** [ahmedmigo/Move-to-library-sketchplugin#14]
When cllicking on library dropdown, UI goes blank

Screen Recording: https://cl.ly/011a1Y3j3y2x

Sketch 51.2, Move to Library 2.2.0

**Comment by Dyphen** [comment]
Same issue, Sketch 51.2, Move to Library 2.2.0

**Comment by ahmedmigo** [comment]
can you right click and inspect on the black screen and click the console tab and show me what is written there ?

**Comment by ahmedmigo** [comment]
@jjmm95  @Dyphen can you check the new update I did fix for this issue. can you check if it is working with you or not v2.2.1

**Comment by swidnikk** [comment]
@ahmedmigo I have the same problem and just had a look. Closing my duplicate issue in a sec
