### ISSUE TITLE
Nested symbols goes crazy :)

### ISSUE THREAD

**Issue by halol** [ahmedmigo/Move-to-library-sketchplugin#2]
Scenario:
I have two files:
`Project.sketch`
`Library.sketch`

1. I've created some symbols in `Library.sketch` and I was using them in the `Project.sketch`.
2. In my `Project` I've created a new component using symbols from `Library` and some new stuff in it.
3. I've created a Symbol from my new component and I used `Move to Library` plugin 
4. I had my `Library` opened so I got this notification that someone is trying to overwrite the file
5. I closed my `Library` and went back again to `Project` to move my symbols to `Library` again
6. I've opened `Library` again and moved symbols were covered with the diagonal red stripes (nested symbols were unlinked and lost)

Apart from that this plugin is a really good idea but need some more work :)
👍

**Comment by ahmedmigo** [comment]
I just pushed a new update 3 mins ago.
can you check again if it working or not
and if you still have the same issue please give me example of your issue

**Comment by ahmedmigo** [comment]
@halol can you check again. I fixed this issue in version 1.4.
if it works fine tell me to close the issue
