### ISSUE TITLE
[Feature request] Relink library 🔗👉🔗

### ISSUE THREAD

**Issue by abrahamnavas** [ahmedmigo/Move-to-library-sketchplugin#3]
It would be absolutely cool if were possible to relink a set of symbols instanced from a given library, to another one that contains the same symbols. 

This is built-in on Sketch and works well when you have those different libraries outside Abstract. But if you want to switch from a library placed locally (or in Dropbox) and want to switch all symbols to a library that lives in Abstract, it doesn't work.

I think it would an awesome feature for your plugin. Just praying to see it implemented 🙏

**Comment by ahmedmigo** [comment]
hello my friend,
i did little update to make it woro please test it and get back to me with your feedback.
best regards

**Comment by ahmedmigo** [comment]
I can add another function that move them but moving all symbols that is also from library it will move everything i bad way, 
like if you have some symbols from the iOS library that is already in sketch it will do it also with all of them

**Comment by abrahamnavas** [comment]
I think maybe I'm misunderstanding the primary function of your plugin: to move symbols from one file (local symbols or library instances) to another file that works as a library.

What I'm looking for is a way to, given a layout file with symbol instances from Library A, select and swap all symbol instances to Library B. Not to actually move any symbol, but swap the library they are referred to. That's what actually Symbol Swapper does.

I thought I could hack that workflow by using your plugin, but maybe I have to use that other plugin that fits better into my scenario.

Thank you very very much for your help and fast support. Can I send you a ☕️ via Paypal or Litecoin?

**Comment by ahmedmigo** [comment]
Oh, this is great feedback. 
I got inspired now for what should be the next update.
so we can add feature of replace library with library.
It is mainly 2 drop downs and from library to library and it do everything for you.

Oh thank you for your coffee ☕️i accept it my paypal is migo_hamada@hotmail.com
