### ISSUE TITLE
Not working on Sketch 50

### ISSUE THREAD

**Issue by pslanca** [ahmedmigo/Move-to-library-sketchplugin#5]

**Comment by okunev** [comment]
Confirm! Menu action just does nothing.

**Comment by ahmedmigo** [comment]
After tracing the problem, I found sketch totally changed the structure of how symbols and libraries work. 
I can't promise for fix soon for it.because the plugin needs to be revamped 😥
I am so sorry for that

**Comment by pslanca** [comment]
@ahmedmigo 😞 Crucial plugin. Hope you find time to fix it.  🙏

**Comment by ahmedmigo** [comment]
@pslanca I know it is very important to me also, I hope I will do it soon :)

**Comment by Lustless** [comment]
Hi @ahmedmigo really love this plugin and is super important in my work, hope you can fix it soon!

**Comment by Matteng123** [comment]
Just love the workflow of adding Symbols to my general libary for later use. i use it a lot. pls fix it ;) saves a lot of time.

**Comment by okunev** [comment]
Hope you will fix your plugin asap. Moving manually is painful!

**Comment by ahmedmigo** [comment]
@all the issue is solved please test it and tell me your feedback

**Comment by romanr** [comment]
@ahmedmigo thank you! Unfortunately I don't see it in Sketch or Sketchpacks. Does it take time for update to appear?

**Comment by Lustless** [comment]
Testing it now and when I hit "move to library" nothing happens. No modal
or anything. I am using Sketch version 50.2, here is a reference:
https://gyazo.com/ae9e2d5f33bd275087a386c3caa2c3ec

**Comment by ahmedmigo** [comment]
@Lustless can you send me which version for the plugin are you in?
