### ISSUE TITLE
Last chosen library

### ISSUE THREAD

**Issue by e1ectron** [ahmedmigo/Move-to-library-sketchplugin#6]
In new dialog window you lost one feature of old native dialogue — last chosen option of select.
Hope you include it or something like that

Thanks for your work anyway :)

**Comment by romanr** [comment]
Yes, this is definitely a step pack in usability. You have to **Remember to choose** library every time. And if you forget and make an error, it's a lot of work to undo the change.

**Comment by ahmedmigo** [comment]
@romanr , @e1ectron  the feature is added in the new version v2.2.0
