### ISSUE TITLE
Issue with Microsoft OneDrive?

### ISSUE THREAD

**Issue by stigmates** [ahmedmigo/Move-to-library-sketchplugin#8]
Hi!

When I work with 100% local imported libraries, no problem it perfectly runs.
But I'm synchronized with OneDrive and I work in my OneDrive folder.
I tried to move a symbol from a current working file to an imported library placed in another subfolder of my OneDrive. It seems it doesn't work. My symbol disapeared from my library; the symbols are still there in my artboards. They're linked to my imported library. But if I choose to edit the symbol into my imported library I can't find it! There's nothing. Weird.
Any idea?
Thx
JC

**Comment by ahmedmigo** [comment]
Hello,
did you open the library file while doing the moving process?
this issue appears when you open the library file and use the plugin. 
you should before using move to library close the move library file.
Check it and let me know

**Comment by stigmates** [comment]
Thanks for answer! It works when I close the target library. Perfect! Great plugin :-)
